remote_paths:
  data: "https://heroku-lyrics-dreamer.s3.amazonaws.com/data_tokenized/"
  checkpoints: "https://heroku-lyrics-dreamer.s3.amazonaws.com/checkpoints/"
local_paths:
  data: "https://heroku-lyrics-dreamer.s3.amazonaws.com/data_tokenized/"
  checkpoints: "https://heroku-lyrics-dreamer.s3.amazonaws.com/checkpoints/"
