config:
  tokenized_data_dict_path: data_tokenized
  learning_rate: 2.81e-5
  lr_scheduler_type: cosine_with_restarts
  weight_decay: 0.00167
  batch_size: 8
  n_training_steps: 300
  n_epochs: 38
  n_warmup_steps: 65
  early_stopping_patience: 1
  n_cosine_cycles: 2
  fp16: true
  seed: 42
